version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    env_file: .env
    command:
      - gunicorn
      - mysite.wsgi:application
      - --bind
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always